### ISSUE TITLE
Support for Authorization and headerParams

### ISSUE THREAD

**Issue by EthanDavis** [epiphone/routing-controllers-openapi#2]
I was wondering what the ETA on the support of routing controllers Authorization and header params was? I see that it's on the TODO at the bottom of the documentation but there isn't any indication of a timeline. BTW really love this library it's saved me so much time!

**Comment by epiphone** [comment]
Hi, there's not really any timeline to speak of, I was sort of hoping the TODOs would inspire a pull request or two... :) Glad you found the library useful!

**Comment by EthanDavis** [comment]
Okay thank you!

**Comment by epiphone** [comment]
Added support for header params in version 1.3.0.

As for authorization, it looks like parsing routing-controller's `@Authorized` decorator into an OpenAPI [Security Scheme object](https://swagger.io/specification/#securitySchemeObject) is not feasible since the decorator only receives a single function as an argument - meaning there's nothing to infer the security scheme from. Feel free to open a PR if you find a solution!
