### ISSUE TITLE
All controllers must be in a single file?

### ISSUE THREAD

**Issue by alexandre-monteiro** [epiphone/routing-controllers-openapi#3]
In your test, there are two controllers on the same file. Is that right?

[controllers.ts](https://github.com/epiphone/routing-controllers-openapi/blob/master/__tests__/fixtures/controllers.ts
)
Do you have an example, maybe a project to show how work with a larger number of controllers?

Thanks

**Comment by epiphone** [comment]
Hi, there's no restriction on which files to place your controllers into. The test controllers you linked to are just bunched together for convenience.

You can take a look at [`routing-controllers` docs](https://github.com/typestack/routing-controllers#example-of-usage) on how to define the controllers.

**Comment by epiphone** [comment]
If I remember correctly, as long as you call `getMetadataArgsStorage()` after defining your `routing-controllers`-decorated controllers, the return value (`storage` in your example above) should contain information for all the controllers. So instead of generating a spec at the end of each controller, you could try generating it right after your `this.express = createExpressServer({ ...` block for example.

Not 100% sure if this was what you're after, lemme know if it doesn't work out for you!
