### ISSUE TITLE
Parameters with @Body are not incuded on the doc

### ISSUE THREAD

**Issue by ollita7** [epiphone/routing-controllers-openapi#7]
I have the followin signature: 
`@Post('/ecs/:ec/ai/:resource')
    async queryResources(@Body() body: AIQueryRequestModel,
        @Param('orgname') orgname: string,
        @Param('ec') ec: string,
        @Param('resource') resource: string)`
When i see the documentation @Body class is not documented

**Comment by epiphone** [comment]
Hi, so the problem is that the `components.schemas.AIQueryRequestModel` field in the resulting OpenAPI schema doesn't get populated? Try first converting `AIQueryRequestModel` into JSON Schema with [`class-validator-jsonschema`](https://github.com/epiphone/class-validator-jsonschema) and then attaching it to your OpenAPI JSON [as exemplified in the docs](https://github.com/epiphone/routing-controllers-openapi#validation-classes). 

Let me know if that doesn't work out for you!

**Comment by ollita7** [comment]
I use your sample. The problem is that my class doesn't have any annotation.
Is it possible to genrate documentation for classes without decorators?

`export class AIQueryRequestModel {
    public dateFrom: string;
    public dateTo: string;
    public filter: any;
    public trend: boolean;
    public trendBy: string;
    public ec: string;
}`

**Comment by epiphone** [comment]
Ah, I see. Currently the library doesn't support documenting classes without annotations, I'm afraid. AFAIK parsing type information is possible only at compile-time which is why we need the annotations.  Doing the same thing at runtime might be doable with [user-defined type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) if you want to give it a shot!
